### ISSUE TITLE
NuGet update?

### ISSUE THREAD

**Issue by creativesuspects** [enkelmedia/Umbraco-SeoVisualizer#10]
Any idea when you'll be pushing the latest commits (fix for title suffix issue and CSS tweaks) to NuGet?

**Comment by dawoe** [comment]
@enkelmedia would be nice to see the latest version released. That would save updating the controller each time. The zip package on our is also behind. That is still on the 8.0.0 version

**Comment by enkelmedia** [comment]
Sorry guys!

I just missed this thread and now it's been almost a year =/

Any way, I've pushed the new version to nuget and our, also added the umbpack-tool which works really nice for simple packages like this.
