### ISSUE TITLE
Updating package with nuget does not update reference to dll

### ISSUE THREAD

**Issue by dawoe** [enkelmedia/Umbraco-SeoVisualizer#5]
Just upgraded from 1.1.0 to 1.2.0 using nuget
The reference (in .csproj) to the dll was not updated and still pointed to the 1.1.0 version of nuget package making my builds fail

**Comment by glombek** [comment]
It looks like the DDL is in the `content` folder rather than the `lib` folder in the package downloaded from NuGet. I suspect this is the issue here.

**Comment by enkelmedia** [comment]
@glombek Maybe you could test an upgrade now after I've release the package with your fixes with the dll and so on?

**Comment by enkelmedia** [comment]
Seems like the new releases works so I’ll close this one.
