### ISSUE TITLE
V8 - compatible version ?

### ISSUE THREAD

**Issue by dawoe** [enkelmedia/Umbraco-SeoVisualizer#7]
Hi @enkelmedia 

Do you have any plans for a V8 compatible version ?

Dave

**Comment by enkelmedia** [comment]
=D 

Sounds like something that would be good =D 

I'll see if I can find some time for this the upcoming weeks =D

// m

**Comment by enkelmedia** [comment]
@dawoe 

Figured you should not have to wait too long =D

https://www.nuget.org/packages/UmbracoSeoVisualizer/8.0.0

https://github.com/enkelmedia/Umbraco-SeoVisualizer/tree/v8
